src/main/java/fr/insee/rmes/api/CodeListsResources.java
src/main/java/fr/insee/rmes/dto/codeList/CodeListNotation.java
src/main/java/fr/insee/rmes/services/codelists/CodeListImpl.java
src/main/resources/queries/codeLists/getCodes.ftlh
src/main/resources/queries/codeLists/getCodesList.ftlh

https://trello.com/c/Mb2SbMYL/1071-ajouter-un-service-sur-une-liste-de-codes

modification service pour être iso avec bauhaus

---

src/main/java/fr/insee/rmes/modelSwagger/dataset/DataSetModelSwagger.java
src/main/java/fr/insee/rmes/modelSwagger/dataset/LabelDataSet.java
src/main/java/fr/insee/rmes/modelSwagger/dataset/Title.java
src/main/java/fr/insee/rmes/services/datasets/DataSetsImpl.java

Titre -> Title
Langue -> Lang
Contenu -> Content
DateModification -> Modified
DateCreation -> Created
StatutValidation -> ValidationState

fix : get /datasets/{id} fields in english instead of french

---

src/main/java/fr/insee/rmes/modelSwagger/concept/ConceptByIdModelSwagger.java
src/main/java/fr/insee/rmes/services/concepts/ConceptsImpl.java
src/main/resources/queries/concepts/getConceptsSdmx.ftlh

modifier le type de la clé conceptsSdmx en Array pour /concept/{id}
https://trello.com/c/k05HxeDV

fix : change ConceptSDMX to return a JSONArray instead of a JSONObject

---

src/main/java/fr/insee/rmes/persistence/RdfService.java
src/main/java/fr/insee/rmes/services/structures/StructuresImpl.java
src/main/java/fr/insee/rmes/utils/config/Config.java
src/main/resources/queries/components/getComponent.ftlh
src/main/resources/rmeswsgi-magma.properties

60 adapt getcomposantid

---

src/main/java/fr/insee/rmes/model/operation/OperationById.java
src/main/java/fr/insee/rmes/model/operation/SerieModel.java
src/main/java/fr/insee/rmes/modelSwagger/operation/OperationByIdModelSwagger.java
src/main/java/fr/insee/rmes/modelSwagger/operation/SerieByIdModelSwagger.java
src/main/java/fr/insee/rmes/services/pogues/PoguesImpl.java
src/main/resources/queries/pogues/getAllCodesLists.ftlh
src/main/resources/queries/pogues/getAllCodesListsSurvey.ftlh
src/main/resources/queries/pogues/getOperationByCode.ftlh
src/test/java/fr/insee/rmes/services/pogues/PoguesImplTest.java

62 add property dccreator

---

src/main/java/fr/insee/rmes/modelSwagger/operation/OperationByIdModelSwagger.java
src/main/java/fr/insee/rmes/services/pogues/PoguesImpl.java
src/main/resources/queries/pogues/getOperationByCode.ftlh

fix about ticket #1389 & Issue [#62 ](https://github.com/InseeFr/Magma/issues/62)

fix : optionnal dc:creator in GetOperationByCode.ftlh

---

src/main/java/fr/insee/rmes/model/concept/ConceptById.java
src/main/java/fr/insee/rmes/modelSwagger/concept/ConceptByIdModelSwagger.java
src/main/java/fr/insee/rmes/services/concepts/ConceptsImpl.java
src/main/resources/queries/concepts/getAllConcepts.ftlh
src/main/resources/queries/concepts/getDetailedConcept.ftlh

84 adapt getconceptid

---

src/main/java/fr/insee/rmes/controller/DataSetResources.java
src/main/java/fr/insee/rmes/services/datasets/DataSetsImpl.java
src/main/java/fr/insee/rmes/services/datasets/DataSetsServices.java
src/main/resources/queries/dataSets/getListDatasets.ftlh

79 adapt getdatasetiddistributions

---

src/main/java/fr/insee/rmes/modelSwagger/concept/ConceptByIdModelSwagger.java
src/main/java/fr/insee/rmes/services/concepts/ConceptsImpl.java
src/main/resources/queries/concepts/getNameADMS.ftlh

87 fix concepts sdmx and name

---

src/main/java/fr/insee/rmes/services/codelists/CodeListImpl.java
src/main/resources/queries/codeLists/getCloseMatch.ftlh
src/main/resources/queries/codeLists/getMatch.ftlh

replaced codesEquivalent by codes and modified codeEquivalent params 
modified and renamed query getCloseMatch.ftlh
#97

fix : adapt get listeCode/id

---

src/main/java/fr/insee/rmes/services/codelists/CodeListImpl.java
src/main/resources/queries/codeLists/getCloseMatch.ftlh
src/main/resources/queries/codeLists/getMatch.ftlh

97 adapter getlistecodeid

---

pom.xml

upgrade spring boot to upgrade lombok to be compliant with java 21

Build with java 21

---

src/main/java/fr/insee/rmes/services/pogues/PoguesImpl.java
src/main/resources/queries/pogues/getAllSeries.ftlh
src/main/resources/queries/pogues/getAllSeriesSurvey.ftlh

fix : put dc:creator optional in service swagger operations/series

---

pom.xml
src/main/java/fr/insee/rmes/controller/CodeListsResources.java
src/main/java/fr/insee/rmes/services/codelists/CodeListImpl.java
src/main/java/fr/insee/rmes/services/codelists/CodeListsServices.java
src/main/java/fr/insee/rmes/utils/config/Config.java
src/main/resources/queries/codeLists/countNumberOfCodes.ftlh
src/main/resources/queries/codeLists/getCodesPagination.ftlh
src/main/resources/rmeswsgi-magma.properties

103 paginer la reponse json pour les listes de codes

---

src/main/java/fr/insee/rmes/controller/CodeListsResources.java
src/main/java/fr/insee/rmes/services/codelists/CodeListImpl.java
src/main/java/fr/insee/rmes/services/codelists/CodeListsServices.java

103 fix error

---

src/main/resources/queries/dataSets/getListDatasets.ftlh

fix : update getListDatasets

---

src/main/resources/queries/dataSets/getDataSetById_catalogueStructures.ftlh

fix: structure for dataset

---

pom.xml
src/test/java/fr/insee/rmes/services/codelists/CodeListImplTest.java

and modify constants writing for json format

Upgrade to java 17

---

src/main/java/fr/insee/rmes/controller/DataSetResources.java
src/main/java/fr/insee/rmes/services/datasets/DataSetsImpl.java
src/main/java/fr/insee/rmes/services/datasets/DataSetsServices.java
src/main/java/fr/insee/rmes/utils/config/Config.java
src/main/resources/rmeswsgi-magma.properties

128 modifier le nombre dobservations dun dataset2

---

src/main/java/fr/insee/rmes/controller/StructuresResources.java
src/main/java/fr/insee/rmes/modelSwagger/structure/StructureSliceKeysModelSwagger.java
src/main/java/fr/insee/rmes/services/structures/StructuresImpl.java
src/main/java/fr/insee/rmes/services/structures/StructuresServices.java
src/main/resources/queries/structures/getStructureSliceKeys.ftlh
src/test/java/fr/insee/rmes/services/structures/StructuresImplTest.java
src/test/java/fr/insee/rmes/services/utils/ResponseUtilsTest.java

Remarque : Comme d'autres end-points (/organisations ou /structures par ex), la doc est erronée : l'exemple devrait être un Array, donc imbriqué entre des crochets [ ]

143 ajout get structure slicekeys

---

src/main/resources/queries/dataSets/getDataSetById_catalogueAdms.ftlh

feat: GET dataset/{id} : add Alternative identifier

---

src/main/java/fr/insee/rmes/services/datasets/DataSetsImpl.java
src/main/resources/queries/dataSets/getDataSetByIdWasDerivedFrom.ftlh
src/main/resources/queries/dataSets/getDataSetById_catalogue.ftlh

fix: wasDerivedFrom for GET dataset/{id}

---

src/main/java/fr/insee/rmes/model/operation/OperationBySerieId.java
src/main/java/fr/insee/rmes/modelSwagger/operation/Serie.java
src/main/java/fr/insee/rmes/services/pogues/PoguesImpl.java
src/main/resources/queries/pogues/getOperationsBySerie.ftlh
src/test/java/fr/insee/rmes/services/pogues/PoguesImplTest.java
src/test/java/fr/insee/rmes/services/utils/PoguesUtilsTest.java

For a series, add acrrualPeriodicity property in the output of operations/serie/{id}/operations

177 ajout de la frquence en sortie du end point operationsserieidoperations

---

src/main/java/fr/insee/rmes/controller/PoguesResources.java

for then end-point GET operations/series
in low-case instead of upper-case (as in prod)

fix: survey parameter

---

src/main/resources/queries/dataSets/getDatasetById/getDataSetById_catalogueAdms.ftlh

fix : split OPTIONAL of getDatasetbyid_catalogieAdms.ftlh in 2 parts

---

src/main/java/fr/insee/rmes/modelSwagger/dataset/DataSetModelSwagger.java
src/main/java/fr/insee/rmes/services/datasets/DataSetsImpl.java
src/main/resources/queries/dataSets/getDatasetById/getDataSetById_catalogue.ftlh
src/test/java/fr/insee/rmes/services/datasets/DataSetsImplTest.java

186 prendre en compte les keyword dans getdatasetid

---

src/main/resources/queries/dataSets/getDatasetById/getDataSetByIdWasGeneratedBy.ftlh
src/main/resources/queries/dataSets/getListDatasets/getListDatasets.ftlh
src/main/resources/queries/organisations/getAllOrganisations.ftlh
src/main/resources/queries/pogues/getOperationByCode.ftlh

fix : replace fr with ${LG1} & en with ${LG2}

---

pom.xml

pom(update springboot)

---

src/main/java/fr/insee/rmes/modelSwagger/dataset/Structure.java
src/main/java/fr/insee/rmes/services/datasets/DataSetsImpl.java
src/main/resources/queries/dataSets/getDatasetById/getDataSetById_catalogueStructures.ftlh
src/test/java/fr/insee/rmes/services/datasets/DataSetsImplTest.java

feat : adapt the structure field get/dataset/id.

---

src/test/java/fr/insee/rmes/services/concepts/ConceptsImplTest.java
src/test/java/fr/insee/rmes/services/utils/ResponseUtilsTest.java

Modify test getCollectionOfConcepts_shouldCreatePartOfTheCorrectMapper

feature : sonar issue

---

impl/src/main/java/fr/insee/rmes/metadata/api/GeoArrondissementMunipalEndpoints.java
impl/src/main/java/fr/insee/rmes/metadata/api/GeoBassinDeVieEndpoints.java
impl/src/main/java/fr/insee/rmes/metadata/api/GeoCantonEndpoints.java
impl/src/main/java/fr/insee/rmes/metadata/api/GeoCantonOuVilleEndpoints.java
impl/src/main/java/fr/insee/rmes/metadata/api/GeoCollectiviteDOutreMerEndpoints.java
impl/src/main/java/fr/insee/rmes/metadata/api/GeoCommuneAssocieeEndpoints.java
impl/src/main/java/fr/insee/rmes/metadata/api/GeoCommuneDelegueeEndpoints.java
impl/src/main/java/fr/insee/rmes/metadata/api/GeoCommuneEndpoints.java
impl/src/main/java/fr/insee/rmes/metadata/api/GeoIntercommunaliteEndpoints.java
impl/src/main/java/fr/insee/rmes/metadata/api/GeoPaysEndpoints.java
impl/src/main/java/fr/insee/rmes/metadata/api/GeoRegionEndpoints.java
impl/src/main/java/fr/insee/rmes/metadata/api/GeoUniteUrbaineEndpoints.java
impl/src/main/java/fr/insee/rmes/metadata/api/GeoZoneDEmploiEndpoints.java
impl/src/main/java/fr/insee/rmes/metadata/queries/parameters/TerritoireEtoileRequestParametizer.java
impl/src/main/java/fr/insee/rmes/metadata/queries/parameters/TerritoireRequestParametizer.java
oas/src/main/resources/openapi.yaml

except for the 3 end-points already done
tests will be developed soon

feat: date * for all concerned end-points

---

impl/src/main/java/fr/insee/rmes/metadata/api/GeoCommuneEndpoints.java
impl/src/main/java/fr/insee/rmes/metadata/api/requestprocessor/RequestProcessor.java
impl/src/main/java/fr/insee/rmes/metadata/queries/QueryBuilder.java
impl/src/main/resources/request/geographie/getCommuneCantonsByCodeDate.ftlh
impl/src/test/java/fr/insee/rmes/metadata/api/testcontainers/queries/GeoCommuneQueriesTest.java
oas/src/main/resources/openapi.yaml

problem for the testshould_return_1_canton_when_CommuneCodeCantons_code14475_date20250904() but it is a problem with the local database (http://localhost:8080/geo/commune/14475/cantons?date=2025-09-04 is OK when executing Magma with data base in dev2)

feat: geo/commune/{code}/cantons
